apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-deployment
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10
